<?php
/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 * 
 */

//generates the nth triangle number
function triangle($max)
{
    return $max * ($max + 1) / 2.0;
}

//print(triangle(1) . "\n");

//print(triangle(7));

//number of divisors a number has

function num_divisors($num)
{
    $count = 0;
    for($i = 1; $i <= $num; $i++)
    {
        if($num % $i == 0)
        {
            $count++;
        }
    }
    
    return $count;
}

//print num_divisors(28);

//first number with more than 500 divisors
$divisors = 0; 
$i = 1;
while($divisors <= 500)
{
    $divisors = num_divisors(triangle($i));
    $i++;
}

print(triangle($i - 1));
?>
