<?php
/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 * 
 */

function is_pentagonal($num)
{
    $pentagon = (1 + sqrt(1 + 24*$num))/6.0;
    if(fmod($pentagon, 1) == 0)
        return true;
    else
        return false;
}
/*
print var_dump(is_pentagonal(22));
print var_dump(is_pentagonal(40755));
print var_dump(is_pentagonal(28));
*/

//generate hexagonal numbers and check if it is also pentagonal 
//(all hexagonal numbers are automatically triangular)

$i = 144;
$found = false;
while(!$found)
{
    $hexagon = $i * (2*$i - 1);
    if(is_pentagonal($hexagon))
    {
        $found = true;
        print $hexagon;
    }
    else
        $i++;
}

?>
